steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'product-service'
      - '--image'
      - 'gcr.io/cloudrun/hello'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'